/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import io.apimatic.examples.SimpleCalculatorClient;
import io.apimatic.examples.exceptions.ApiException;
import io.apimatic.examples.testing.TestHelper;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class APIControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static SimpleCalculatorClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static APIController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getAPIController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Test case for Calculate.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testBasicSumTest() throws Exception {
        // Parameters for the API call
        String operation = 
                "sum";
        double number1 = 1d;
        double number2 = 2d;

        // Set callback and perform API call
        try {
            controller.calculate(operation, number1, number2);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Calculate.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testBasicMultiplyTest() throws Exception {
        // Parameters for the API call
        String operation = 
                "multiply";
        double number1 = 4d;
        double number2 = 3d;

        // Set callback and perform API call
        double result = 0;
        try {
            result = controller.calculate(operation, number1, number2);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "12",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

}
