/*
 * SimpleCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package io.apimatic.examples.controllers;

import io.apimatic.examples.ApiHelper;
import io.apimatic.examples.AuthManager;
import io.apimatic.examples.Configuration;
import io.apimatic.examples.Server;
import io.apimatic.examples.exceptions.ApiException;
import io.apimatic.examples.http.Headers;
import io.apimatic.examples.http.client.HttpCallback;
import io.apimatic.examples.http.client.HttpClient;
import io.apimatic.examples.http.client.HttpContext;
import io.apimatic.examples.http.request.HttpRequest;
import io.apimatic.examples.http.response.HttpResponse;
import io.apimatic.examples.http.response.HttpStringResponse;
import java.io.IOException;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * This class lists all the endpoints of the groups.
 */
public final class APIController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public APIController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }

    /**
     * Initializes the controller with HTTPCallback.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     * @param httpCallback    Callback to be called before and after the HTTP call.
     */
    public APIController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        super(config, httpClient, authManagers, httpCallback);
    }

    /**
     * @param  operation  Required parameter: The operation to be applied on the operands
     * @param  number1  Required parameter: Example: 1
     * @param  number2  Required parameter: Example: 1
     * @return    Returns the Double response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Double calculate(
            final String operation,
            final double number1,
            final double number2) throws ApiException, IOException {
        HttpRequest request = buildCalculateRequest(operation, number1, number2);
        authManagers.get("global").apply(request);

        HttpResponse response = getClientInstance().executeAsString(request);
        HttpContext context = new HttpContext(request, response);

        return handleCalculateResponse(context);
    }

    /**
     * @param  operation  Required parameter: The operation to be applied on the operands
     * @param  number1  Required parameter: Example: 1
     * @param  number2  Required parameter: Example: 1
     * @return    Returns the Double response from the API call
     */
    public CompletableFuture<Double> calculateAsync(
            final String operation,
            final double number1,
            final double number2) {
        return makeHttpCallAsync(() -> buildCalculateRequest(operation, number1, number2),
            req -> authManagers.get("global").applyAsync(req)
                .thenCompose(request -> getClientInstance()
                        .executeAsStringAsync(request)),
            context -> handleCalculateResponse(context));
    }

    /**
     * Builds the HttpRequest object for calculate.
     */
    private HttpRequest buildCalculateRequest(
            final String operation,
            final double number1,
            final double number2) {
        //the base uri for api requests
        String baseUri = config.getBaseUri(Server.ENUM_DEFAULT);

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/{operation}");

        //process template parameters
        Map<String, SimpleEntry<Object, Boolean>> templateParameters = new HashMap<>();
        templateParameters.put("operation",
                new SimpleEntry<Object, Boolean>(operation, true));
        ApiHelper.appendUrlWithTemplateParameters(queryBuilder, templateParameters);

        //load all query parameters
        Map<String, Object> queryParameters = new HashMap<>();
        queryParameters.put("number1", number1);
        queryParameters.put("number2", number2);

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("user-agent", BaseController.userAgent);

        //prepare and invoke the API call request to fetch the response
        HttpRequest request = getClientInstance().get(queryBuilder, headers, queryParameters,
                null);

        // Invoke the callback before request if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onBeforeRequest(request);
        }

        return request;
    }

    /**
     * Processes the response for calculate.
     * @return An object of type double
     */
    private Double handleCalculateResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onAfterResponse(context);
        }

        //Error handling using HTTP status codes
        int responseCode = response.getStatusCode();

        if (responseCode == 400) {
            throw new ApiException("operand not found", context);
        }
        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        String responseBody = ((HttpStringResponse) response).getBody();
        double result = Double.parseDouble(responseBody);

        return result;
    }

}